"""``data/sources/legislation/catalogue.json`` — generated by ``sd corpus ingest``, never hand-edited.

One entry per downloaded consolidated text. The files themselves live at
``data/sources/legislation/<jurisdiction>/<language>/<global_id>.akt`` and are
byte-identical copies of what Riigi Teataja served; ``sha256`` pins them.
"""

from __future__ import annotations

import json
import re
import unicodedata
from pathlib import Path

from pydantic import BaseModel, Field

CATALOGUE_FILE = "catalogue.json"


class CatalogueEntry(BaseModel):
    jurisdiction: str  # "ee"
    language: str  # "en" (RT V translation) | "et" (RT I original)
    source: str = "riigiteataja"
    act_group_id: str  # <terviktekstiGrupiID>: stable across redactions; links en <-> et
    global_id: str  # <globaalID>: this consolidated text
    title: str
    act_slug: str  # English act slug; the statute id vocabulary
    document_type: str = ""  # <dokumentLiik>, e.g. "seadus"
    text_type: str = ""  # <tekstiliik>, e.g. "terviktekst"
    adopted_on: str = ""  # <vastuvoetud/aktikuupaev>
    entry_into_force: str = ""  # <vastuvoetud/joustumine> — the act's original entry into force
    in_force_from: str = ""  # <kehtivus/kehtivuseAlgus> — this redaction's window
    in_force_until: str | None = None  # <kehtivus/kehtivuseLopp>; null when open
    original_publication: str = ""  # the act's first publication (RT I …); same in every language
    publication: str = ""  # this text's own RT reference, e.g. "RT V, 05.01.2026, 5"
    schema_name: str = ""  # <skeemiNimi>
    source_url: str = ""
    file: str  # relative to the corpus directory, e.g. "ee/en/505012026005.akt"
    sha256: str
    size_bytes: int
    downloaded_at: str  # source file mtime (UTC, ISO 8601)
    ingested_at: str
    counterparts: list[str] = Field(default_factory=list)  # global_ids, other language, same group

    @property
    def key(self) -> tuple[str, str]:
        return (self.act_slug, self.language)


class Catalogue(BaseModel):
    generated_by: str = "sd corpus ingest"
    note: str = (
        "Generated file — do not hand-edit. Entries are consolidated texts from Riigi Teataja; "
        "the .akt files are byte-identical copies pinned by sha256."
    )
    entries: list[CatalogueEntry] = Field(default_factory=list)

    # -- persistence ------------------------------------------------------------

    @classmethod
    def load(cls, path: Path | str) -> Catalogue:
        path = Path(path)
        if not path.exists():
            return cls()
        return cls.model_validate(json.loads(path.read_text(encoding="utf-8")))

    def save(self, path: Path | str) -> None:
        self.entries.sort(key=lambda e: (e.act_slug, e.language, e.global_id))
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        Path(path).write_text(
            json.dumps(self.model_dump(mode="json"), indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )

    # -- lookup -------------------------------------------------------------

    def by_global_id(self, global_id: str) -> CatalogueEntry | None:
        for entry in self.entries:
            if entry.global_id == global_id:
                return entry
        return None

    def by_slug(self, act_slug: str, language: str | None = None) -> list[CatalogueEntry]:
        return [
            e
            for e in self.entries
            if e.act_slug == act_slug and (language is None or e.language == language)
        ]

    def group(self, act_group_id: str) -> list[CatalogueEntry]:
        return [e for e in self.entries if e.act_group_id == act_group_id]

    def act_slugs(self) -> list[str]:
        return sorted({e.act_slug for e in self.entries})

    def upsert(self, entry: CatalogueEntry) -> None:
        self.entries = [e for e in self.entries if e.global_id != entry.global_id]
        self.entries.append(entry)


def slugify_title(title: str) -> str:
    """``"Land Tax Act"`` -> ``land_tax_act``; diacritics in a source-language title are stripped (NFKD) before slugging."""
    text = unicodedata.normalize("NFKD", title)
    text = "".join(ch for ch in text if not unicodedata.combining(ch))
    text = re.sub(r"[^A-Za-z0-9]+", "_", text).strip("_").lower()
    if not text or not text[0].isalpha():
        text = "act_" + text
    return text


__all__ = ["CATALOGUE_FILE", "Catalogue", "CatalogueEntry", "slugify_title"]
