"""The corpus directory: ``data/sources/legislation/`` — files + generated catalogue.

Layout::

    data/sources/legislation/
      catalogue.json                 generated by ``sd corpus ingest``; never hand-edited
      ee/en/<global_id>.akt          byte-identical Riigi Teataja XML (RT V translations)
      ee/et/<global_id>.akt          byte-identical Riigi Teataja XML (RT I originals)

``ingest`` copies a downloaded file in, parses its metadata and writes the
catalogue entry; ``check`` re-hashes every file and reports drift. Nothing
here ever edits an ``.akt`` file.
"""

from __future__ import annotations

import re
import shutil
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path

from statute_decider.legislation.catalogue import (
    CATALOGUE_FILE,
    Catalogue,
    CatalogueEntry,
    slugify_title,
)
from statute_decider.legislation.riigiteataja import (
    Act,
    ActMetadata,
    load_act,
    parse_metadata,
    sha256_of,
)

CORPUS_RELATIVE = Path("data") / "sources" / "legislation"
JURISDICTION = "ee"
_INTERIM_NAME_RE = re.compile(r"^(?P<jur>[a-z]{2})-(?P<lang>[a-z]{2})-(?P<act>[a-z0-9_]+)\.txt$")


def _iso_utc(ts: float) -> str:
    return datetime.fromtimestamp(ts, UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


def _now() -> str:
    return datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


def act_key(meta: ActMetadata | CatalogueEntry) -> tuple[str, str]:
    """What links the translation to the original: the act's adoption date and its
    first RT I publication, both identical across languages. (``terviktekstiGrupiID``
    turned out to be per language in the files at hand.)"""
    return (meta.adopted_on, meta.original_publication)


class Corpus:
    """Read/write access to one corpus directory."""

    def __init__(self, root: Path | str) -> None:
        self.root = Path(root)
        self.catalogue_path = self.root / CATALOGUE_FILE
        self._catalogue: Catalogue | None = None
        self._acts: dict[str, Act] = {}

    # -- catalogue ----------------------------------------------------------------

    @property
    def catalogue(self) -> Catalogue:
        if self._catalogue is None:
            self._catalogue = Catalogue.load(self.catalogue_path)
        return self._catalogue

    def save(self) -> None:
        self._relink()
        self.catalogue.save(self.catalogue_path)

    def path_of(self, entry: CatalogueEntry) -> Path:
        return self.root / entry.file

    def entry(self, global_id: str) -> CatalogueEntry:
        found = self.catalogue.by_global_id(global_id)
        if found is None:
            raise KeyError(f"Corpus has no consolidated text {global_id}")
        return found

    def entry_for(self, act_slug: str, language: str | None = None) -> CatalogueEntry:
        entries = self.catalogue.by_slug(act_slug, language)
        if not entries:
            raise KeyError(f"Corpus has no act {act_slug!r}" + (f" in {language}" if language else ""))
        if len(entries) > 1:
            raise KeyError(f"Corpus has {len(entries)} texts for {act_slug!r}; pass a language or global_id")
        return entries[0]

    # -- acts ----------------------------------------------------------------------

    def load(self, global_id: str) -> Act:
        if global_id not in self._acts:
            entry = self.entry(global_id)
            act = load_act(self.path_of(entry))
            if act.sha256 != entry.sha256:
                raise ValueError(
                    f"{entry.file}: sha256 {act.sha256[:12]}… differs from the catalogue "
                    f"({entry.sha256[:12]}…); run `sd corpus check`"
                )
            self._acts[global_id] = act
        return self._acts[global_id]

    # -- ingest ----------------------------------------------------------------------

    def ingest(
        self,
        source: Path | str,
        url: str,
        *,
        act_slug: str | None = None,
        force: bool = False,
    ) -> CatalogueEntry:
        """Copy ``source`` into the corpus and (re)write its catalogue entry.

        The English slug comes from the English title; an Estonian text takes
        the slug of its English counterpart (same ``act_key``), falling back to a
        slug of its own title until the counterpart is ingested.
        """
        source = Path(source)
        meta = parse_metadata(source)
        if not meta.global_id:
            raise ValueError(f"{source}: no <globaalID>")
        dest_rel = Path(JURISDICTION) / meta.language / f"{meta.global_id}.akt"
        dest = self.root / dest_rel
        digest = sha256_of(source)
        if dest.exists() and sha256_of(dest) != digest and not force:
            raise FileExistsError(
                f"{dest_rel} exists with different content; pass force=True to replace it"
            )
        dest.parent.mkdir(parents=True, exist_ok=True)
        if not dest.exists() or sha256_of(dest) != digest:
            shutil.copyfile(source, dest)
        slug = act_slug or self._slug_for(meta)
        counterparts = [
            e.global_id
            for e in self.catalogue.entries
            if act_key(e) == act_key(meta) and e.language != meta.language
        ]
        entry = CatalogueEntry(
            jurisdiction=JURISDICTION,
            language=meta.language,
            act_group_id=meta.group_id,
            global_id=meta.global_id,
            title=meta.title,
            act_slug=slug,
            document_type=meta.document_type,
            text_type=meta.text_type,
            adopted_on=meta.adopted_on,
            entry_into_force=meta.entry_into_force,
            in_force_from=meta.in_force_from,
            in_force_until=meta.in_force_until,
            original_publication=meta.original_publication,
            publication=meta.publication,
            schema_name=meta.schema,
            source_url=url,
            file=dest_rel.as_posix(),
            sha256=digest,
            size_bytes=source.stat().st_size,
            downloaded_at=_iso_utc(source.stat().st_mtime),
            ingested_at=_now(),
            counterparts=sorted(counterparts),
        )
        self.catalogue.upsert(entry)
        self._relink()
        self.catalogue.save(self.catalogue_path)
        self._acts.pop(meta.global_id, None)
        return self.catalogue.by_global_id(meta.global_id)  # type: ignore[return-value]

    def _slug_for(self, meta: ActMetadata) -> str:
        if meta.language == "en":
            return slugify_title(meta.title)
        english = [
            e for e in self.catalogue.entries
            if e.language == "en" and act_key(e) == act_key(meta)
        ]
        return english[0].act_slug if english else slugify_title(meta.title)

    def _relink(self) -> None:
        cat = self.catalogue
        for entry in cat.entries:
            entry.counterparts = sorted(
                e.global_id
                for e in cat.entries
                if e.global_id != entry.global_id
                and e.language != entry.language
                and act_key(e) == act_key(entry)
            )
        for entry in cat.entries:
            if entry.language != "en":
                english = [
                    e for e in cat.entries if e.language == "en" and act_key(e) == act_key(entry)
                ]
                if english:
                    entry.act_slug = english[0].act_slug

    def ingest_dir(self, directory: Path | str, *, force: bool = False) -> list[CatalogueEntry]:
        """Ingest every ``<jur>-<lang>-<act>.txt`` interim catalogue file in ``directory``
        (line 1 = official URL, line 2 = file name under ``<directory>/<lang>/``).
        English files first so the Estonian ones inherit the slug."""
        directory = Path(directory)
        items: list[tuple[str, Path, str]] = []
        for txt in sorted(directory.glob("*.txt")):
            match = _INTERIM_NAME_RE.match(txt.name)
            if not match:
                continue
            lines = [line.strip() for line in txt.read_text(encoding="utf-8").splitlines() if line.strip()]
            if len(lines) < 2:
                raise ValueError(f"{txt}: expected URL on line 1 and file name on line 2")
            url, name = lines[0], lines[1]
            path = directory / match.group("lang") / name
            if not path.exists():
                raise FileNotFoundError(f"{txt} names {name}, but {path} does not exist")
            items.append((match.group("lang"), path, url))
        items.sort(key=lambda item: (item[0] != "en", item[1].name))
        return [self.ingest(path, url, force=force) for _, path, url in items]

    # -- check -----------------------------------------------------------------------

    def check(self) -> CheckReport:
        report = CheckReport()
        cat = self.catalogue
        seen: set[Path] = set()
        for entry in cat.entries:
            path = self.path_of(entry)
            seen.add(path.resolve())
            if not path.exists():
                report.errors.append(f"{entry.file}: missing")
                continue
            digest = sha256_of(path)
            if digest != entry.sha256:
                report.errors.append(f"{entry.file}: sha256 changed ({entry.sha256[:12]}… -> {digest[:12]}…)")
            size = path.stat().st_size
            if size != entry.size_bytes:
                report.errors.append(f"{entry.file}: size {entry.size_bytes} -> {size}")
            try:
                meta = parse_metadata(path)
            except Exception as exc:  # noqa: BLE001
                report.errors.append(f"{entry.file}: does not parse: {exc}")
                continue
            if meta.global_id != entry.global_id:
                report.errors.append(f"{entry.file}: <globaalID> {meta.global_id} != {entry.global_id}")
            if entry.in_force_until:
                report.info.append(
                    f"{entry.act_slug}/{entry.language} ({entry.global_id}): validity window "
                    f"{entry.in_force_from} – {entry.in_force_until} has an end date"
                )
        for path in sorted((self.root / JURISDICTION).rglob("*.akt")) if (self.root / JURISDICTION).exists() else []:
            if path.resolve() not in seen:
                report.errors.append(f"{path.relative_to(self.root)}: not in the catalogue")
        # per act: windows differ across languages; counterparts missing; structural diff
        for slug in cat.act_slugs():
            entries = cat.by_slug(slug)
            langs = {e.language for e in entries}
            if len(langs) < 2:
                report.info.append(f"{slug}: only {sorted(langs)} present (no counterpart)")
            windows = {(e.in_force_from, e.in_force_until) for e in entries}
            if len(windows) > 1:
                detail = "; ".join(
                    f"{e.language} {e.in_force_from} – {e.in_force_until or 'open'}" for e in entries
                )
                report.info.append(f"{slug}: validity windows differ across languages: {detail}")
            if len(entries) == 2 and not report.errors:
                a, b = (self.load(e.global_id) for e in entries)
                only_a = sorted(set(a.index) - set(b.index))
                only_b = sorted(set(b.index) - set(a.index))
                if only_a or only_b:
                    report.info.append(
                        f"{slug}: provision sets differ — {len(only_a)} only in "
                        f"{a.metadata.language}, {len(only_b)} only in {b.metadata.language} "
                        f"(e.g. {', '.join((only_a + only_b)[:4])})"
                    )
        report.entries = len(cat.entries)
        return report


@dataclass
class CheckReport:
    entries: int = 0
    errors: list[str] = field(default_factory=list)
    info: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.errors

    def render(self) -> str:
        lines = [f"{'FAIL' if self.errors else 'OK'}: {self.entries} catalogue entries"]
        lines += [f"  ERROR {e}" for e in self.errors]
        lines += [f"  info  {i}" for i in self.info]
        return "\n".join(lines)


__all__ = ["CORPUS_RELATIVE", "JURISDICTION", "CheckReport", "Corpus", "act_key"]
